name: Test pull request

on:
  pull_request:
    branches:
      - master
      - beta
      - "[0-9]+.[0-9x]+"
      - "[0-9]+.[0-9x]+.x"

env:
  node-version: "12.x"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Get Yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn dependencies
        uses: actions/cache@v1
        id: cache-yarn
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile --silent

      - name: Start test
        run: yarn test --forceExit --silent --onlyChanged
